##Domain Overview

The intended users of the system are prospective undergraduate students and lecturers of the Faculty of Science. Prospective students should register for an examination by filling an online application given at the end of the assignment. 
Assume that undergraduate studies will be offered in eight subjects: Botany, Chemistry, Computer Science, Geology, Mathematics, and Molecular biology, Physics, Statistics and Zoology. For each subject a collection of courses are offered in each of the two semesters. Registered students could be able to sit for any examination conducted for any semester. Generally, there are multiple examinations per course per semester. Your system must facilitate students to select any of such exams. When students are sitting for an examination, answers must be automatically submitted at the end of the allowed time period so that students cannot work after that.
Examinations are generated by instructors who teach courses. The system should have features to generate an exam by editing an online paper. In other words, there should be facilities for instructors to create MCQ and short answer questions for a selected course. In case of MCQs instructor must be able to edit the question and set of answers. For short answer questions they edit the question and the answer. Once an instructor created a paper, it should be stored in a database. When an examination is over instructor will mark the paper online. In marking, instructor login and enter the registration number of a student. 
Functions that should be provided by the System

	1. A home page for users to login and signing. If it is a signing display the application for users to fill.
	2. The system should provide access to three types of users 
		a. Undergraduate student.
		b. An instructor
		c. Administrator
	3. For each user, provide the following functionalities.

1. Students

	The prospective students should be given interfaces:
	1. To fill the application for signing. A sample application is given at the end of this. 
	2. To view and edit submitted applications
	3. To apply for an exam and to sit for a registered examination and answer the paper. Allow students to save the answers occasionally.
	4. To check marks for a given examination by specifying the year, semester, subject, course code and examination (quiz, mid-semester and end-semester).

2. Lecturer/Instructor:

	The lecturer should be able to display all the students who have registered for the courses that the lecturer handles. He/she should be able: 

	1. To view the list of students who have registered for a specific course.
	2. To edit an examination paper for a given semester, subject, examination (quiz, mid-semester and end-semester) and a course code.
	3. To view and mark exam answers submitted by a given student
	4. To view results summary of a given course. Your system should not allow the undergraduate students and other instructors to view details of student marks. 
	5. To create examination papers and mark the answers provided by students. In this case, the following facilities are need
		i) Facilities to create a paper by editing.
		ii) Once the lecturer enters the student’s registration number, the paper with provided answers must be loaded. MCQs must be automatically marked. Short answer questions are marked by the lecturer. The loaded paper should include facilities for assigning marks for Short answer questions and then sum them up along with automatically marked MCQs. 

3. Administrator
Administrator should be able to manage all users. In particular, the Administrator should be able to assign courses for instructors. Once a student or instructor submitted an application, administrator must approve it. Students are allowed sit for exam and instructors are allowed to create and mark papers, only once the approval is given. If an application rejected, relevant data should be deleted from the database.  






































